version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: daily
    allow:
      - dependency-type: all
    groups:
      compatible:
        update-types: [minor, patch]
        patterns: ['*']
      security:
        applies-to: security-updates
        patterns: ['*']
    commit-message:
      prefix: build
      include: scope
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: ci
      include: scope
