name: Merge tested dependencies
on:
  workflow_run:
    workflows: [CI]
    types: [completed]
permissions:
  contents: write
  pull-requests: write
  actions: write
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: legra-ai/github-actions/.github/actions/merge-tested-dependabot@main
